export const LOGIN_ACTION = "LOGIN_ACTION";
export const LOGOUT_ACTION = "LOGOUT_ACTION"
export const LOGIN_ERROR_ACTION = "LOGIN_ERROR_ACTION"

export const CLEAR_TODO_LIST_ACTION = "CLEAR_TODO_LIST_ACTION";

export const LOAD_TODO_LIST_REQUEST_ACTION = "LOAD_TODO_LIST_REQUEST_ACTION";
export const LOAD_TODO_LIST_SUCCESS_ACTION = "LOAD_TODO_LIST_SUCCESS_ACTION";
export const LOAD_TODO_LIST_FAILURE_ACTION = "LOAD_TODO_LIST_FAILURE_ACTION";

export const ADD_TODO_ACTION = "ADD_TODO_ACTION";
export const EDIT_TODO_ACTION = "EDIT_TODO_ACTION";
export const DELETE_TODO_ACTION = "DELETE_TODO_ACTION";

export const SYNC_TODO_LIST_REQUEST_ACTION = "SYNC_TODO_LIST_REQUEST_ACTION";
export const SYNC_TODO_LIST_SUCCESS_ACTION = "SYNC_TODO_LIST_SUCCESS_ACTION";
export const SYNC_TODO_LIST_FAILURE_ACTION = "SYNC_TODO_LIST_FAILURE_ACTION";
export const SYNC_TODO_LIST_IDLE_ACTION = "SYNC_TODO_LIST_IDLE_ACTION";